### ISSUE TITLE
Quoted string arguments and spaces

### ISSUE THREAD

**Issue by mrchimp** [c9s/GetOptionKit#43] opened 2016-05-29 16:15 UTC
The library doesn't appear to support arguments such as

```
command --option="foo bar baz"
```

This becomes

```
['"foo', 'bar', 'baz"']
```

...rather than

```
['foo bar baz']
```

Is this something that you are planning to/want to implement?

**Comment by c9s** [comment] 2016-05-29 17:07
Yeah I think this should be fixed. Does this line below work?

    command --option "foo bar baz"

**Comment by mrchimp** [comment] 2016-05-29 19:53
I get the same results.

A small correction: I actually get

    'keys' => [
        'option' => '"foo'
    ]

    'arguments' => [
        'bar',
        'baz"'
    ]

...but it's the same with or without the `=`.

**Comment by mrchimp** [comment] 2016-05-29 20:11
Also, in case it helps (or if I'm doing something wrong) the spec I am using is:

    $specs->add('o|option:', 'Test option' );
          ->isa('String');

**Comment by c9s** [comment] 2016-07-13 09:36
This needs to be fixed, the case below should be fixed:

```
php test.php --option="foo bar baz"                                                     

array(2) {
  [0] =>
  string(8) "test.php"
  [1] =>
  string(20) "--option=foo bar baz"
}
```

**Comment by c9s** [comment] 2016-07-18 06:57
@mrchimp 

I've verified this case, however I can't reproduce your issue, here is my sample code:

```php
<?php
require 'vendor/autoload.php';
use GetOptionKit\OptionCollection;
use GetOptionKit\ContinuousOptionParser;
use GetOptionKit\OptionParser;

var_dump($argv);

$options = new OptionCollection;
// $options->add("v|verbose")->isa("number")->incremental();// Setting isa("number") will throw an InvalidOptionValue exception "Invalid value for -v, --verbose. Requires a type Number."
$options->add("v|verbose")->incremental();// This works but only sets the value to true even if specified multiple times
$options->add("foo:", "foo");

// $parser = new ContinuousOptionParser($options);// Replace ContinuousOptionParser with OptionParser and everything works as expected
$parser = new OptionParser($options);// Replace ContinuousOptionParser with OptionParser and everything works as expected
$result = $parser->parse($argv);
var_dump($result->get('foo'));
```

```
php test.php --foo="aa bb cc"
```

**Comment by mrchimp** [comment] 2016-07-18 09:08
Ok, thank you for confirming. I must be doing something wrong. I'll have
another look.

**Comment by mrchimp** [comment] 2016-07-24 11:04
Ok, this was my fault. Sorry! Problem is I'm not passing `$argv` to GetOptionKit, I'm doing something like this:

```
$input = 'foo bar="lorem ipsum"';
$input_parts = explode(' ', $input); // <--- bad!
$result = $parser->parse($input_parts);
```

I need to parse a string into an `$argv` style array. Is this something that GetOptionKit handles?

**Comment by schnittstabil** [comment] 2017-04-20 09:18
> I need to parse a string into an `$argv` style array.

That depends on your platform/shell; `sh`/`bash`/… and `cmd.exe` differ in several aspects.

For example `foo\ bar`:
* on Linux: `['foo bar']`
* on Windows: `['foo\', 'bar']`

**Closed** 2017-05-19 16:39 UTC
Labels: Bug
